-- Aggiunge le colonne necessarie alla tabella Entrate_merci nel database Tirelli_40
-- Eseguire una volta sola su SQL Server

USE [Tirelli_40]
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Entrate_merci' AND COLUMN_NAME = 'DDT_Numero')
    ALTER TABLE [dbo].[Entrate_merci] ADD [DDT_Numero] NVARCHAR(50) NULL
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Entrate_merci' AND COLUMN_NAME = 'DDT_Data')
    ALTER TABLE [dbo].[Entrate_merci] ADD [DDT_Data] DATE NULL
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Entrate_merci' AND COLUMN_NAME = 'Fornitore')
    ALTER TABLE [dbo].[Entrate_merci] ADD [Fornitore] NVARCHAR(200) NULL
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Entrate_merci' AND COLUMN_NAME = 'Ordine_Acquisto')
    ALTER TABLE [dbo].[Entrate_merci] ADD [Ordine_Acquisto] NVARCHAR(100) NULL
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Entrate_merci' AND COLUMN_NAME = 'Codice_Articolo')
    ALTER TABLE [dbo].[Entrate_merci] ADD [Codice_Articolo] NVARCHAR(100) NULL
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Entrate_merci' AND COLUMN_NAME = 'Disegno')
    ALTER TABLE [dbo].[Entrate_merci] ADD [Disegno] NVARCHAR(100) NULL
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Entrate_merci' AND COLUMN_NAME = 'Descrizione')
    ALTER TABLE [dbo].[Entrate_merci] ADD [Descrizione] NVARCHAR(500) NULL
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Entrate_merci' AND COLUMN_NAME = 'UM')
    ALTER TABLE [dbo].[Entrate_merci] ADD [UM] NVARCHAR(20) NULL
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Entrate_merci' AND COLUMN_NAME = 'Quantita')
    ALTER TABLE [dbo].[Entrate_merci] ADD [Quantita] DECIMAL(18,4) NULL
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Entrate_merci' AND COLUMN_NAME = 'PDF_File')
    ALTER TABLE [dbo].[Entrate_merci] ADD [PDF_File] NVARCHAR(500) NULL
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Entrate_merci' AND COLUMN_NAME = 'Data_Inserimento')
    ALTER TABLE [dbo].[Entrate_merci] ADD [Data_Inserimento] DATETIME NULL DEFAULT GETDATE()
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Entrate_merci' AND COLUMN_NAME = 'Utente')
    ALTER TABLE [dbo].[Entrate_merci] ADD [Utente] NVARCHAR(100) NULL
GO

PRINT 'Modifica tabella Entrate_merci completata.'
GO
